--- 
title: 'Making maps for conservation - GIF and interactive maps '
author: "Emilie Dedeban"
date: "`r Sys.Date()`"
description: |
  This is a minimal example of using the bookdown package to write a book.
  set in the _output.yml file.
  The HTML output format for this example is bookdown::gitbook,
documentclass: book
github-repo: rstudio/bookdown-demo
link-citations: yes
site: bookdown::bookdown_site
bibliography:
- book.bib
- packages.bib
---

# Introduction

Creating a map has many benefits. Firstly, it allows to get information that is not visible or difficult to understand in a table. Secondly, it makes the subject more interesting. With the development of mapping tools, it is now possible to make animated map, or even collaborative. In this manual you will learn how to make a GIF and a collaborative map. These types of tools are essential assets for presentations, but also for discussions with collaborators. In the field of conservation, the use of maps allows to answer questions about human-wildlife conflict, but also to understand the distribution of animal and plant species, to better protect them.

The following code will allow to:
* create a map with the ```sf``` package \linebreak 

* import data from an open access dataset \linebreak 

* create a GIF with ```gganimate``` \linebreak 

* create an interactive map with ```leaflet``` 

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
